#!/bin/bash
set -euo pipefail

SECRETS_FILE="/var/mnt/storage/ghost-compose/.env.secrets"
GENERATED_FILE="/var/mnt/storage/ghost-compose/.env.generated"
COMPOSE_DIR="/etc/ghost-compose"
CONFIG_FILE="${COMPOSE_DIR}/.env.config"

# Ensure .env.generated exists (prevents ghost-compose.service failure if we exit early)
touch "$GENERATED_FILE"
chmod 0600 "$GENERATED_FILE"

# Check if admin token is available
if ! grep -q "TINYBIRD_ADMIN_TOKEN=" "$SECRETS_FILE" 2>/dev/null; then
    echo "TINYBIRD_ADMIN_TOKEN not found in .env.secrets, skipping TinyBird provisioning..."
    echo "Add TINYBIRD_ADMIN_TOKEN to .env.secrets to enable TinyBird analytics."
    exit 0
fi

# Source the secrets to get TINYBIRD_ADMIN_TOKEN and TINYBIRD_API_URL
set -a
source "$SECRETS_FILE"
set +a

# Export as TB_TOKEN/TB_HOST for tb CLI (avoids exposing values in process listing)
export TB_TOKEN="${TINYBIRD_ADMIN_TOKEN}"
export TB_HOST="${TINYBIRD_API_URL:-https://api.tinybird.co}"

cd "$COMPOSE_DIR"

# Docker compose needs env files for variable interpolation
COMPOSE_CMD="docker compose --env-file ${CONFIG_FILE} --env-file ${SECRETS_FILE} --env-file ${GENERATED_FILE}"

echo "=== TinyBird Provisioning ==="

# 1. Sync TinyBird schema files from Ghost image
echo "[1/4] Syncing TinyBird files from Ghost..."
$COMPOSE_CMD run --rm tinybird-sync

# 2. Deploy datasources and pipes (idempotent)
echo "[2/4] Deploying TinyBird datasources and pipes..."
$COMPOSE_CMD run --rm -e TB_TOKEN -e TB_HOST \
    tinybird-cli --cloud deploy --allow-destructive-operations

# 3. Extract tracker token and workspace ID
echo "[3/4] Extracting tokens and workspace ID..."

# Save shell options and disable tracing to prevent token exposure in logs
OLD_OPTS=$(set +o)
{ set +x; } 2>/dev/null

# Get all tokens in JSON format
JSON_TOKENS=$($COMPOSE_CMD run --rm -e TB_TOKEN -e TB_HOST \
    tinybird-cli --cloud token ls --format json)

# Get workspace ID
WORKSPACE_ID=$($COMPOSE_CMD run --rm -e TB_TOKEN -e TB_HOST \
    tinybird-cli --cloud workspace current --format json | jq -r '.id')

# Extract tracker token from JSON
TRACKER_TOKEN=$(echo "$JSON_TOKENS" | jq -r '.[] | select(.name=="tracker") | .token')

EXTRACT_FAILED=""

if [ -z "$TRACKER_TOKEN" ] || [ "$TRACKER_TOKEN" = "null" ]; then
    EXTRACT_FAILED="tracker token"
fi

if [ -z "$WORKSPACE_ID" ] || [ "$WORKSPACE_ID" = "null" ]; then
    EXTRACT_FAILED="${EXTRACT_FAILED:+$EXTRACT_FAILED and }workspace ID"
fi

# 4. Write generated environment file (only if both extractions succeeded)
if [ -z "$EXTRACT_FAILED" ]; then
    cat > "$GENERATED_FILE" << EOF
# Auto-generated by tinybird-provision.service - DO NOT EDIT
# Regenerated on every boot - $(date)
TINYBIRD_TRACKER_TOKEN=${TRACKER_TOKEN}
TINYBIRD_WORKSPACE_ID=${WORKSPACE_ID}
TINYBIRD_API_URL=${TINYBIRD_API_URL:-https://api.tinybird.co}
COMPOSE_PROFILES=analytics
EOF
else
    # Write empty file to prevent docker compose errors (analytics disabled)
    echo "# TinyBird provisioning failed - $(date)" > "$GENERATED_FILE"
fi

chmod 0600 "$GENERATED_FILE"

# Clear sensitive variables
unset JSON_TOKENS TRACKER_TOKEN WORKSPACE_ID TB_TOKEN

# Restore shell options
eval "$OLD_OPTS"

# Handle errors after restoring options (safe to log now)
if [ -n "$EXTRACT_FAILED" ]; then
    echo "WARNING: Could not extract ${EXTRACT_FAILED}. Analytics disabled."
    exit 0
fi

echo "[4/4] Writing .env.generated... done"

echo "=== TinyBird Provisioning Complete ==="
