#!/bin/bash
set -euo pipefail

SECRETS_FILE="/var/mnt/storage/ghost-compose/.env.secrets"
GENERATED_FILE="/var/mnt/storage/ghost-compose/.env.generated"
COMPOSE_DIR="/etc/ghost-compose"

# Check if admin token is available
if ! grep -q "TINYBIRD_ADMIN_TOKEN=" "$SECRETS_FILE" 2>/dev/null; then
    echo "TINYBIRD_ADMIN_TOKEN not found in .env.secrets, skipping TinyBird provisioning..."
    echo "Add TINYBIRD_ADMIN_TOKEN to .env.secrets to enable TinyBird analytics."
    # Create empty .env.generated to prevent docker compose errors
    touch "$GENERATED_FILE"
    exit 0
fi

# Source the secrets to get TINYBIRD_ADMIN_TOKEN and TINYBIRD_API_URL
set -a
source "$SECRETS_FILE"
set +a

# Export as TB_TOKEN/TB_HOST for tb CLI (avoids exposing values in process listing)
export TB_TOKEN="${TINYBIRD_ADMIN_TOKEN}"
export TB_HOST="${TINYBIRD_API_URL:-https://api.tinybird.co}"

cd "$COMPOSE_DIR"

echo "=== TinyBird Provisioning ==="

# 1. Sync TinyBird schema files from Ghost image
echo "[1/4] Syncing TinyBird files from Ghost..."
docker compose run --rm tinybird-sync

# 2. Deploy datasources and pipes (idempotent)
echo "[2/4] Deploying TinyBird datasources and pipes..."
docker compose run --rm -e TB_TOKEN -e TB_HOST \
    tinybird-cli deploy --cloud --allow-destructive-operations

# 3. Extract tracker token and workspace ID
echo "[3/4] Extracting tokens and workspace ID..."

# Save shell options and disable tracing to prevent token exposure in logs
OLD_OPTS=$(set +o)
{ set +x; } 2>/dev/null

# Get all tokens in JSON format
JSON_TOKENS=$(docker compose run --rm -e TB_TOKEN -e TB_HOST \
    tinybird-cli token ls --format json)

# Get workspace ID
WORKSPACE_ID=$(docker compose run --rm -e TB_TOKEN -e TB_HOST \
    tinybird-cli workspace current --format json | jq -r '.id')

# Extract tracker token from JSON
TRACKER_TOKEN=$(echo "$JSON_TOKENS" | jq -r '.[] | select(.name=="tracker") | .token')

TOKEN_EXTRACT_FAILED=""
WORKSPACE_EXTRACT_FAILED=""

if [ -z "$TRACKER_TOKEN" ] || [ "$TRACKER_TOKEN" = "null" ]; then
    TOKEN_EXTRACT_FAILED="true"
fi

if [ -z "$WORKSPACE_ID" ] || [ "$WORKSPACE_ID" = "null" ]; then
    WORKSPACE_EXTRACT_FAILED="true"
fi

# 4. Write generated environment file
cat > "$GENERATED_FILE" << EOF
# Auto-generated by tinybird-provision.service - DO NOT EDIT
# Regenerated on every boot - $(date)
TINYBIRD_TRACKER_TOKEN=${TRACKER_TOKEN}
TINYBIRD_WORKSPACE_ID=${WORKSPACE_ID}
TINYBIRD_API_URL=${TINYBIRD_API_URL:-https://api.tinybird.co}
COMPOSE_PROFILES=analytics
EOF

chmod 0600 "$GENERATED_FILE"

# Clear sensitive variables
unset JSON_TOKENS TRACKER_TOKEN WORKSPACE_ID TB_TOKEN

# Restore shell options
eval "$OLD_OPTS"

# Handle warnings/errors after restoring options (safe to log now)
if [ -n "$TOKEN_EXTRACT_FAILED" ]; then
    echo "WARNING: Could not extract tracker token. Analytics may not work."
    echo "# TinyBird token extraction failed - $(date)" > "$GENERATED_FILE"
    exit 0
fi

if [ -n "$WORKSPACE_EXTRACT_FAILED" ]; then
    echo "WARNING: Could not extract workspace ID. Stats may not work."
fi

echo "[4/4] Writing .env.generated... done"

echo "=== TinyBird Provisioning Complete ==="
