# Generated by scripts/tofu.sh — do not edit by hand.
bucket   = "${BUCKET}"
key      = "${KEY}"

# Cloudflare R2 endpoint (account-scoped)
endpoint = "https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com"

# R2 isn't in AWS regions; pick a placeholder AWS region
region = "us-east-1"

# Compatibility flags for non-AWS S3
use_path_style              = true
skip_credentials_validation = true
skip_metadata_api_check     = true
skip_region_validation      = true
skip_requesting_account_id  = true